version: '3.8'
services:
  api:
    container_name: api
    build: .
    command: bash -c "npm run build && npm run start"
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}'

  db:
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/var/lib/mongodb/data

volumes:
  mongo-data:
