version: '3.8'
services:
  api:
    container_name: api
    build: .
    command: bash -c "npm run db:upgrade && npm run start"
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}'

  db:
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
