version: '3.8'
networks:
  api-network:
    driver: bridge
services:
  api:
    container_name: api
    build: .
    command: bash -c "npm run build && npm run start"
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: 'mongodb://db/express-ts-test'
    networks:
      - api-network

  db:
    container_name: db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/var/lib/mongodb/data
    networks:
      - api-network

volumes:
  mongo-data:
