name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  presubmit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20.6.0'
    - name: setup
      run: |
        npm install
    - name: Compile TS files
      run: |
        npm run build
    - name: test
      run: |
        npm run test